// Code generated by entc, DO NOT EDIT.

package model

import (
	"context"
	"errors"
	"fmt"
	"mall-go/app/user/service/internal/data/model/predicate"
	"mall-go/app/user/service/internal/data/model/userwalletdetail"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserWalletDetailQuery is the builder for querying UserWalletDetail entities.
type UserWalletDetailQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserWalletDetail
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserWalletDetailQuery builder.
func (uwdq *UserWalletDetailQuery) Where(ps ...predicate.UserWalletDetail) *UserWalletDetailQuery {
	uwdq.predicates = append(uwdq.predicates, ps...)
	return uwdq
}

// Limit adds a limit step to the query.
func (uwdq *UserWalletDetailQuery) Limit(limit int) *UserWalletDetailQuery {
	uwdq.limit = &limit
	return uwdq
}

// Offset adds an offset step to the query.
func (uwdq *UserWalletDetailQuery) Offset(offset int) *UserWalletDetailQuery {
	uwdq.offset = &offset
	return uwdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uwdq *UserWalletDetailQuery) Unique(unique bool) *UserWalletDetailQuery {
	uwdq.unique = &unique
	return uwdq
}

// Order adds an order step to the query.
func (uwdq *UserWalletDetailQuery) Order(o ...OrderFunc) *UserWalletDetailQuery {
	uwdq.order = append(uwdq.order, o...)
	return uwdq
}

// First returns the first UserWalletDetail entity from the query.
// Returns a *NotFoundError when no UserWalletDetail was found.
func (uwdq *UserWalletDetailQuery) First(ctx context.Context) (*UserWalletDetail, error) {
	nodes, err := uwdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userwalletdetail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uwdq *UserWalletDetailQuery) FirstX(ctx context.Context) *UserWalletDetail {
	node, err := uwdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserWalletDetail ID from the query.
// Returns a *NotFoundError when no UserWalletDetail ID was found.
func (uwdq *UserWalletDetailQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = uwdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userwalletdetail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uwdq *UserWalletDetailQuery) FirstIDX(ctx context.Context) int64 {
	id, err := uwdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Last returns the last UserWalletDetail entity from the query.
// Returns a *NotFoundError when no UserWalletDetail was found.
func (uwdq *UserWalletDetailQuery) Last(ctx context.Context) (*UserWalletDetail, error) {
	nodes, err := uwdq.All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userwalletdetail.Label}
	}
	return nodes[len(nodes)-1], nil
}

// LastX is like Last, but panics if an error occurs.
func (uwdq *UserWalletDetailQuery) LastX(ctx context.Context) *UserWalletDetail {
	node, err := uwdq.Last(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// LastID returns the last UserWalletDetail ID from the query.
// Returns a *NotFoundError when no UserWalletDetail ID was found.
func (uwdq *UserWalletDetailQuery) LastID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = uwdq.IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userwalletdetail.Label}
		return
	}
	return ids[len(ids)-1], nil
}

// LastIDX is like LastID, but panics if an error occurs.
func (uwdq *UserWalletDetailQuery) LastIDX(ctx context.Context) int64 {
	id, err := uwdq.LastID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserWalletDetail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UserWalletDetail entity is not found.
// Returns a *NotFoundError when no UserWalletDetail entities are found.
func (uwdq *UserWalletDetailQuery) Only(ctx context.Context) (*UserWalletDetail, error) {
	nodes, err := uwdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userwalletdetail.Label}
	default:
		return nil, &NotSingularError{userwalletdetail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uwdq *UserWalletDetailQuery) OnlyX(ctx context.Context) *UserWalletDetail {
	node, err := uwdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserWalletDetail ID in the query.
// Returns a *NotSingularError when exactly one UserWalletDetail ID is not found.
// Returns a *NotFoundError when no entities are found.
func (uwdq *UserWalletDetailQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = uwdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userwalletdetail.Label}
	default:
		err = &NotSingularError{userwalletdetail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uwdq *UserWalletDetailQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := uwdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserWalletDetails.
func (uwdq *UserWalletDetailQuery) All(ctx context.Context) ([]*UserWalletDetail, error) {
	if err := uwdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uwdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uwdq *UserWalletDetailQuery) AllX(ctx context.Context) []*UserWalletDetail {
	nodes, err := uwdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserWalletDetail IDs.
func (uwdq *UserWalletDetailQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := uwdq.Select(userwalletdetail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uwdq *UserWalletDetailQuery) IDsX(ctx context.Context) []int64 {
	ids, err := uwdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uwdq *UserWalletDetailQuery) Count(ctx context.Context) (int, error) {
	if err := uwdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uwdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uwdq *UserWalletDetailQuery) CountX(ctx context.Context) int {
	count, err := uwdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uwdq *UserWalletDetailQuery) Exist(ctx context.Context) (bool, error) {
	if err := uwdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uwdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uwdq *UserWalletDetailQuery) ExistX(ctx context.Context) bool {
	exist, err := uwdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserWalletDetailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uwdq *UserWalletDetailQuery) Clone() *UserWalletDetailQuery {
	if uwdq == nil {
		return nil
	}
	return &UserWalletDetailQuery{
		config:     uwdq.config,
		limit:      uwdq.limit,
		offset:     uwdq.offset,
		order:      append([]OrderFunc{}, uwdq.order...),
		predicates: append([]predicate.UserWalletDetail{}, uwdq.predicates...),
		// clone intermediate query.
		sql:  uwdq.sql.Clone(),
		path: uwdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserWalletDetail.Query().
//		GroupBy(userwalletdetail.FieldCreateTime).
//		Aggregate(model.Count()).
//		Scan(ctx, &v)
//
func (uwdq *UserWalletDetailQuery) GroupBy(field string, fields ...string) *UserWalletDetailGroupBy {
	group := &UserWalletDetailGroupBy{config: uwdq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uwdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uwdq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.UserWalletDetail.Query().
//		Select(userwalletdetail.FieldCreateTime).
//		Scan(ctx, &v)
//
func (uwdq *UserWalletDetailQuery) Select(fields ...string) *UserWalletDetailSelect {
	uwdq.fields = append(uwdq.fields, fields...)
	return &UserWalletDetailSelect{UserWalletDetailQuery: uwdq}
}

func (uwdq *UserWalletDetailQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uwdq.fields {
		if !userwalletdetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("model: invalid field %q for query", f)}
		}
	}
	if uwdq.path != nil {
		prev, err := uwdq.path(ctx)
		if err != nil {
			return err
		}
		uwdq.sql = prev
	}
	return nil
}

func (uwdq *UserWalletDetailQuery) sqlAll(ctx context.Context) ([]*UserWalletDetail, error) {
	var (
		nodes = []*UserWalletDetail{}
		_spec = uwdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserWalletDetail{config: uwdq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("model: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, uwdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uwdq *UserWalletDetailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uwdq.querySpec()
	return sqlgraph.CountNodes(ctx, uwdq.driver, _spec)
}

func (uwdq *UserWalletDetailQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := uwdq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("model: check existence: %w", err)
	}
	return n > 0, nil
}

func (uwdq *UserWalletDetailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userwalletdetail.Table,
			Columns: userwalletdetail.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: userwalletdetail.FieldID,
			},
		},
		From:   uwdq.sql,
		Unique: true,
	}
	if unique := uwdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uwdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userwalletdetail.FieldID)
		for i := range fields {
			if fields[i] != userwalletdetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uwdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uwdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uwdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uwdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uwdq *UserWalletDetailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uwdq.driver.Dialect())
	t1 := builder.Table(userwalletdetail.Table)
	columns := uwdq.fields
	if len(columns) == 0 {
		columns = userwalletdetail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uwdq.sql != nil {
		selector = uwdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range uwdq.predicates {
		p(selector)
	}
	for _, p := range uwdq.order {
		p(selector)
	}
	if offset := uwdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uwdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserWalletDetailGroupBy is the group-by builder for UserWalletDetail entities.
type UserWalletDetailGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uwdgb *UserWalletDetailGroupBy) Aggregate(fns ...AggregateFunc) *UserWalletDetailGroupBy {
	uwdgb.fns = append(uwdgb.fns, fns...)
	return uwdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (uwdgb *UserWalletDetailGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := uwdgb.path(ctx)
	if err != nil {
		return err
	}
	uwdgb.sql = query
	return uwdgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uwdgb *UserWalletDetailGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := uwdgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (uwdgb *UserWalletDetailGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(uwdgb.fields) > 1 {
		return nil, errors.New("model: UserWalletDetailGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := uwdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uwdgb *UserWalletDetailGroupBy) StringsX(ctx context.Context) []string {
	v, err := uwdgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uwdgb *UserWalletDetailGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uwdgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userwalletdetail.Label}
	default:
		err = fmt.Errorf("model: UserWalletDetailGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uwdgb *UserWalletDetailGroupBy) StringX(ctx context.Context) string {
	v, err := uwdgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (uwdgb *UserWalletDetailGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(uwdgb.fields) > 1 {
		return nil, errors.New("model: UserWalletDetailGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := uwdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uwdgb *UserWalletDetailGroupBy) IntsX(ctx context.Context) []int {
	v, err := uwdgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uwdgb *UserWalletDetailGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uwdgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userwalletdetail.Label}
	default:
		err = fmt.Errorf("model: UserWalletDetailGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uwdgb *UserWalletDetailGroupBy) IntX(ctx context.Context) int {
	v, err := uwdgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (uwdgb *UserWalletDetailGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(uwdgb.fields) > 1 {
		return nil, errors.New("model: UserWalletDetailGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := uwdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uwdgb *UserWalletDetailGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := uwdgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uwdgb *UserWalletDetailGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uwdgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userwalletdetail.Label}
	default:
		err = fmt.Errorf("model: UserWalletDetailGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uwdgb *UserWalletDetailGroupBy) Float64X(ctx context.Context) float64 {
	v, err := uwdgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (uwdgb *UserWalletDetailGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(uwdgb.fields) > 1 {
		return nil, errors.New("model: UserWalletDetailGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := uwdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uwdgb *UserWalletDetailGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := uwdgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uwdgb *UserWalletDetailGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uwdgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userwalletdetail.Label}
	default:
		err = fmt.Errorf("model: UserWalletDetailGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uwdgb *UserWalletDetailGroupBy) BoolX(ctx context.Context) bool {
	v, err := uwdgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uwdgb *UserWalletDetailGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range uwdgb.fields {
		if !userwalletdetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uwdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uwdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uwdgb *UserWalletDetailGroupBy) sqlQuery() *sql.Selector {
	selector := uwdgb.sql.Select()
	aggregation := make([]string, 0, len(uwdgb.fns))
	for _, fn := range uwdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(uwdgb.fields)+len(uwdgb.fns))
		for _, f := range uwdgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(uwdgb.fields...)...)
}

// UserWalletDetailSelect is the builder for selecting fields of UserWalletDetail entities.
type UserWalletDetailSelect struct {
	*UserWalletDetailQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uwds *UserWalletDetailSelect) Scan(ctx context.Context, v interface{}) error {
	if err := uwds.prepareQuery(ctx); err != nil {
		return err
	}
	uwds.sql = uwds.UserWalletDetailQuery.sqlQuery(ctx)
	return uwds.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uwds *UserWalletDetailSelect) ScanX(ctx context.Context, v interface{}) {
	if err := uwds.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (uwds *UserWalletDetailSelect) Strings(ctx context.Context) ([]string, error) {
	if len(uwds.fields) > 1 {
		return nil, errors.New("model: UserWalletDetailSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := uwds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uwds *UserWalletDetailSelect) StringsX(ctx context.Context) []string {
	v, err := uwds.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (uwds *UserWalletDetailSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uwds.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userwalletdetail.Label}
	default:
		err = fmt.Errorf("model: UserWalletDetailSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uwds *UserWalletDetailSelect) StringX(ctx context.Context) string {
	v, err := uwds.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (uwds *UserWalletDetailSelect) Ints(ctx context.Context) ([]int, error) {
	if len(uwds.fields) > 1 {
		return nil, errors.New("model: UserWalletDetailSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := uwds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uwds *UserWalletDetailSelect) IntsX(ctx context.Context) []int {
	v, err := uwds.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (uwds *UserWalletDetailSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uwds.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userwalletdetail.Label}
	default:
		err = fmt.Errorf("model: UserWalletDetailSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uwds *UserWalletDetailSelect) IntX(ctx context.Context) int {
	v, err := uwds.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (uwds *UserWalletDetailSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(uwds.fields) > 1 {
		return nil, errors.New("model: UserWalletDetailSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := uwds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uwds *UserWalletDetailSelect) Float64sX(ctx context.Context) []float64 {
	v, err := uwds.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (uwds *UserWalletDetailSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uwds.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userwalletdetail.Label}
	default:
		err = fmt.Errorf("model: UserWalletDetailSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uwds *UserWalletDetailSelect) Float64X(ctx context.Context) float64 {
	v, err := uwds.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (uwds *UserWalletDetailSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(uwds.fields) > 1 {
		return nil, errors.New("model: UserWalletDetailSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := uwds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uwds *UserWalletDetailSelect) BoolsX(ctx context.Context) []bool {
	v, err := uwds.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (uwds *UserWalletDetailSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uwds.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userwalletdetail.Label}
	default:
		err = fmt.Errorf("model: UserWalletDetailSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uwds *UserWalletDetailSelect) BoolX(ctx context.Context) bool {
	v, err := uwds.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uwds *UserWalletDetailSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uwds.sql.Query()
	if err := uwds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
