// Code generated by entc, DO NOT EDIT.

package model

import (
	"mall-go/app/app/service/internal/data/ent/schema"
	"mall-go/app/app/service/internal/data/model/activity"
	"mall-go/app/app/service/internal/data/model/banner"
	"mall-go/app/app/service/internal/data/model/banneritem"
	"mall-go/app/app/service/internal/data/model/brand"
	"mall-go/app/app/service/internal/data/model/category"
	"mall-go/app/app/service/internal/data/model/charge"
	"mall-go/app/app/service/internal/data/model/coupon"
	"mall-go/app/app/service/internal/data/model/coupontemplate"
	"mall-go/app/app/service/internal/data/model/coupontype"
	"mall-go/app/app/service/internal/data/model/gridcategory"
	"mall-go/app/app/service/internal/data/model/order"
	"mall-go/app/app/service/internal/data/model/orderdetail"
	"mall-go/app/app/service/internal/data/model/ordersub"
	"mall-go/app/app/service/internal/data/model/refund"
	"mall-go/app/app/service/internal/data/model/saleexplain"
	"mall-go/app/app/service/internal/data/model/sku"
	"mall-go/app/app/service/internal/data/model/speckey"
	"mall-go/app/app/service/internal/data/model/specvalue"
	"mall-go/app/app/service/internal/data/model/spu"
	"mall-go/app/app/service/internal/data/model/spudetailimg"
	"mall-go/app/app/service/internal/data/model/spuimg"
	"mall-go/app/app/service/internal/data/model/tag"
	"mall-go/app/app/service/internal/data/model/theme"
	"mall-go/app/app/service/internal/data/model/user"
	"mall-go/app/app/service/internal/data/model/usercoupon"
	"mall-go/app/app/service/internal/data/model/userfavor"
	"mall-go/app/app/service/internal/data/model/userinfo"
	"mall-go/app/app/service/internal/data/model/userpoint"
	"mall-go/app/app/service/internal/data/model/userpointdetail"
	"mall-go/app/app/service/internal/data/model/userwallet"
	"mall-go/app/app/service/internal/data/model/userwalletdetail"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	activityMixin := schema.Activity{}.Mixin()
	activityMixinFields0 := activityMixin[0].Fields()
	_ = activityMixinFields0
	activityFields := schema.Activity{}.Fields()
	_ = activityFields
	// activityDescCreateTime is the schema descriptor for create_time field.
	activityDescCreateTime := activityMixinFields0[0].Descriptor()
	// activity.DefaultCreateTime holds the default value on creation for the create_time field.
	activity.DefaultCreateTime = activityDescCreateTime.Default.(func() time.Time)
	// activityDescUpdateTime is the schema descriptor for update_time field.
	activityDescUpdateTime := activityMixinFields0[1].Descriptor()
	// activity.DefaultUpdateTime holds the default value on creation for the update_time field.
	activity.DefaultUpdateTime = activityDescUpdateTime.Default.(func() time.Time)
	// activity.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	activity.UpdateDefaultUpdateTime = activityDescUpdateTime.UpdateDefault.(func() time.Time)
	bannerMixin := schema.Banner{}.Mixin()
	bannerMixinFields0 := bannerMixin[0].Fields()
	_ = bannerMixinFields0
	bannerFields := schema.Banner{}.Fields()
	_ = bannerFields
	// bannerDescCreateTime is the schema descriptor for create_time field.
	bannerDescCreateTime := bannerMixinFields0[0].Descriptor()
	// banner.DefaultCreateTime holds the default value on creation for the create_time field.
	banner.DefaultCreateTime = bannerDescCreateTime.Default.(func() time.Time)
	// bannerDescUpdateTime is the schema descriptor for update_time field.
	bannerDescUpdateTime := bannerMixinFields0[1].Descriptor()
	// banner.DefaultUpdateTime holds the default value on creation for the update_time field.
	banner.DefaultUpdateTime = bannerDescUpdateTime.Default.(func() time.Time)
	// banner.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	banner.UpdateDefaultUpdateTime = bannerDescUpdateTime.UpdateDefault.(func() time.Time)
	banneritemMixin := schema.BannerItem{}.Mixin()
	banneritemMixinFields0 := banneritemMixin[0].Fields()
	_ = banneritemMixinFields0
	banneritemFields := schema.BannerItem{}.Fields()
	_ = banneritemFields
	// banneritemDescCreateTime is the schema descriptor for create_time field.
	banneritemDescCreateTime := banneritemMixinFields0[0].Descriptor()
	// banneritem.DefaultCreateTime holds the default value on creation for the create_time field.
	banneritem.DefaultCreateTime = banneritemDescCreateTime.Default.(func() time.Time)
	// banneritemDescUpdateTime is the schema descriptor for update_time field.
	banneritemDescUpdateTime := banneritemMixinFields0[1].Descriptor()
	// banneritem.DefaultUpdateTime holds the default value on creation for the update_time field.
	banneritem.DefaultUpdateTime = banneritemDescUpdateTime.Default.(func() time.Time)
	// banneritem.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	banneritem.UpdateDefaultUpdateTime = banneritemDescUpdateTime.UpdateDefault.(func() time.Time)
	brandMixin := schema.Brand{}.Mixin()
	brandMixinFields0 := brandMixin[0].Fields()
	_ = brandMixinFields0
	brandFields := schema.Brand{}.Fields()
	_ = brandFields
	// brandDescCreateTime is the schema descriptor for create_time field.
	brandDescCreateTime := brandMixinFields0[0].Descriptor()
	// brand.DefaultCreateTime holds the default value on creation for the create_time field.
	brand.DefaultCreateTime = brandDescCreateTime.Default.(func() time.Time)
	// brandDescUpdateTime is the schema descriptor for update_time field.
	brandDescUpdateTime := brandMixinFields0[1].Descriptor()
	// brand.DefaultUpdateTime holds the default value on creation for the update_time field.
	brand.DefaultUpdateTime = brandDescUpdateTime.Default.(func() time.Time)
	// brand.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	brand.UpdateDefaultUpdateTime = brandDescUpdateTime.UpdateDefault.(func() time.Time)
	categoryMixin := schema.Category{}.Mixin()
	categoryMixinFields0 := categoryMixin[0].Fields()
	_ = categoryMixinFields0
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreateTime is the schema descriptor for create_time field.
	categoryDescCreateTime := categoryMixinFields0[0].Descriptor()
	// category.DefaultCreateTime holds the default value on creation for the create_time field.
	category.DefaultCreateTime = categoryDescCreateTime.Default.(func() time.Time)
	// categoryDescUpdateTime is the schema descriptor for update_time field.
	categoryDescUpdateTime := categoryMixinFields0[1].Descriptor()
	// category.DefaultUpdateTime holds the default value on creation for the update_time field.
	category.DefaultUpdateTime = categoryDescUpdateTime.Default.(func() time.Time)
	// category.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	category.UpdateDefaultUpdateTime = categoryDescUpdateTime.UpdateDefault.(func() time.Time)
	chargeMixin := schema.Charge{}.Mixin()
	chargeMixinFields0 := chargeMixin[0].Fields()
	_ = chargeMixinFields0
	chargeFields := schema.Charge{}.Fields()
	_ = chargeFields
	// chargeDescCreateTime is the schema descriptor for create_time field.
	chargeDescCreateTime := chargeMixinFields0[0].Descriptor()
	// charge.DefaultCreateTime holds the default value on creation for the create_time field.
	charge.DefaultCreateTime = chargeDescCreateTime.Default.(func() time.Time)
	// chargeDescUpdateTime is the schema descriptor for update_time field.
	chargeDescUpdateTime := chargeMixinFields0[1].Descriptor()
	// charge.DefaultUpdateTime holds the default value on creation for the update_time field.
	charge.DefaultUpdateTime = chargeDescUpdateTime.Default.(func() time.Time)
	// charge.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	charge.UpdateDefaultUpdateTime = chargeDescUpdateTime.UpdateDefault.(func() time.Time)
	couponMixin := schema.Coupon{}.Mixin()
	couponMixinFields0 := couponMixin[0].Fields()
	_ = couponMixinFields0
	couponFields := schema.Coupon{}.Fields()
	_ = couponFields
	// couponDescCreateTime is the schema descriptor for create_time field.
	couponDescCreateTime := couponMixinFields0[0].Descriptor()
	// coupon.DefaultCreateTime holds the default value on creation for the create_time field.
	coupon.DefaultCreateTime = couponDescCreateTime.Default.(func() time.Time)
	// couponDescUpdateTime is the schema descriptor for update_time field.
	couponDescUpdateTime := couponMixinFields0[1].Descriptor()
	// coupon.DefaultUpdateTime holds the default value on creation for the update_time field.
	coupon.DefaultUpdateTime = couponDescUpdateTime.Default.(func() time.Time)
	// coupon.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	coupon.UpdateDefaultUpdateTime = couponDescUpdateTime.UpdateDefault.(func() time.Time)
	coupontemplateMixin := schema.CouponTemplate{}.Mixin()
	coupontemplateMixinFields0 := coupontemplateMixin[0].Fields()
	_ = coupontemplateMixinFields0
	coupontemplateFields := schema.CouponTemplate{}.Fields()
	_ = coupontemplateFields
	// coupontemplateDescCreateTime is the schema descriptor for create_time field.
	coupontemplateDescCreateTime := coupontemplateMixinFields0[0].Descriptor()
	// coupontemplate.DefaultCreateTime holds the default value on creation for the create_time field.
	coupontemplate.DefaultCreateTime = coupontemplateDescCreateTime.Default.(func() time.Time)
	// coupontemplateDescUpdateTime is the schema descriptor for update_time field.
	coupontemplateDescUpdateTime := coupontemplateMixinFields0[1].Descriptor()
	// coupontemplate.DefaultUpdateTime holds the default value on creation for the update_time field.
	coupontemplate.DefaultUpdateTime = coupontemplateDescUpdateTime.Default.(func() time.Time)
	// coupontemplate.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	coupontemplate.UpdateDefaultUpdateTime = coupontemplateDescUpdateTime.UpdateDefault.(func() time.Time)
	coupontypeMixin := schema.CouponType{}.Mixin()
	coupontypeMixinFields0 := coupontypeMixin[0].Fields()
	_ = coupontypeMixinFields0
	coupontypeFields := schema.CouponType{}.Fields()
	_ = coupontypeFields
	// coupontypeDescCreateTime is the schema descriptor for create_time field.
	coupontypeDescCreateTime := coupontypeMixinFields0[0].Descriptor()
	// coupontype.DefaultCreateTime holds the default value on creation for the create_time field.
	coupontype.DefaultCreateTime = coupontypeDescCreateTime.Default.(func() time.Time)
	// coupontypeDescUpdateTime is the schema descriptor for update_time field.
	coupontypeDescUpdateTime := coupontypeMixinFields0[1].Descriptor()
	// coupontype.DefaultUpdateTime holds the default value on creation for the update_time field.
	coupontype.DefaultUpdateTime = coupontypeDescUpdateTime.Default.(func() time.Time)
	// coupontype.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	coupontype.UpdateDefaultUpdateTime = coupontypeDescUpdateTime.UpdateDefault.(func() time.Time)
	gridcategoryMixin := schema.GridCategory{}.Mixin()
	gridcategoryMixinFields0 := gridcategoryMixin[0].Fields()
	_ = gridcategoryMixinFields0
	gridcategoryFields := schema.GridCategory{}.Fields()
	_ = gridcategoryFields
	// gridcategoryDescCreateTime is the schema descriptor for create_time field.
	gridcategoryDescCreateTime := gridcategoryMixinFields0[0].Descriptor()
	// gridcategory.DefaultCreateTime holds the default value on creation for the create_time field.
	gridcategory.DefaultCreateTime = gridcategoryDescCreateTime.Default.(func() time.Time)
	// gridcategoryDescUpdateTime is the schema descriptor for update_time field.
	gridcategoryDescUpdateTime := gridcategoryMixinFields0[1].Descriptor()
	// gridcategory.DefaultUpdateTime holds the default value on creation for the update_time field.
	gridcategory.DefaultUpdateTime = gridcategoryDescUpdateTime.Default.(func() time.Time)
	// gridcategory.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	gridcategory.UpdateDefaultUpdateTime = gridcategoryDescUpdateTime.UpdateDefault.(func() time.Time)
	orderMixin := schema.Order{}.Mixin()
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreateTime is the schema descriptor for create_time field.
	orderDescCreateTime := orderMixinFields0[0].Descriptor()
	// order.DefaultCreateTime holds the default value on creation for the create_time field.
	order.DefaultCreateTime = orderDescCreateTime.Default.(func() time.Time)
	// orderDescUpdateTime is the schema descriptor for update_time field.
	orderDescUpdateTime := orderMixinFields0[1].Descriptor()
	// order.DefaultUpdateTime holds the default value on creation for the update_time field.
	order.DefaultUpdateTime = orderDescUpdateTime.Default.(func() time.Time)
	// order.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	order.UpdateDefaultUpdateTime = orderDescUpdateTime.UpdateDefault.(func() time.Time)
	// orderDescOrderNo is the schema descriptor for order_no field.
	orderDescOrderNo := orderFields[0].Descriptor()
	// order.OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	order.OrderNoValidator = orderDescOrderNo.Validators[0].(func(string) error)
	orderdetailMixin := schema.OrderDetail{}.Mixin()
	orderdetailMixinFields0 := orderdetailMixin[0].Fields()
	_ = orderdetailMixinFields0
	orderdetailFields := schema.OrderDetail{}.Fields()
	_ = orderdetailFields
	// orderdetailDescCreateTime is the schema descriptor for create_time field.
	orderdetailDescCreateTime := orderdetailMixinFields0[0].Descriptor()
	// orderdetail.DefaultCreateTime holds the default value on creation for the create_time field.
	orderdetail.DefaultCreateTime = orderdetailDescCreateTime.Default.(func() time.Time)
	// orderdetailDescUpdateTime is the schema descriptor for update_time field.
	orderdetailDescUpdateTime := orderdetailMixinFields0[1].Descriptor()
	// orderdetail.DefaultUpdateTime holds the default value on creation for the update_time field.
	orderdetail.DefaultUpdateTime = orderdetailDescUpdateTime.Default.(func() time.Time)
	// orderdetail.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	orderdetail.UpdateDefaultUpdateTime = orderdetailDescUpdateTime.UpdateDefault.(func() time.Time)
	// orderdetailDescPayWay is the schema descriptor for pay_way field.
	orderdetailDescPayWay := orderdetailFields[1].Descriptor()
	// orderdetail.DefaultPayWay holds the default value on creation for the pay_way field.
	orderdetail.DefaultPayWay = orderdetailDescPayWay.Default.(int)
	// orderdetailDescClientType is the schema descriptor for client_type field.
	orderdetailDescClientType := orderdetailFields[2].Descriptor()
	// orderdetail.DefaultClientType holds the default value on creation for the client_type field.
	orderdetail.DefaultClientType = orderdetailDescClientType.Default.(int)
	ordersubMixin := schema.OrderSub{}.Mixin()
	ordersubMixinFields0 := ordersubMixin[0].Fields()
	_ = ordersubMixinFields0
	ordersubFields := schema.OrderSub{}.Fields()
	_ = ordersubFields
	// ordersubDescCreateTime is the schema descriptor for create_time field.
	ordersubDescCreateTime := ordersubMixinFields0[0].Descriptor()
	// ordersub.DefaultCreateTime holds the default value on creation for the create_time field.
	ordersub.DefaultCreateTime = ordersubDescCreateTime.Default.(func() time.Time)
	// ordersubDescUpdateTime is the schema descriptor for update_time field.
	ordersubDescUpdateTime := ordersubMixinFields0[1].Descriptor()
	// ordersub.DefaultUpdateTime holds the default value on creation for the update_time field.
	ordersub.DefaultUpdateTime = ordersubDescUpdateTime.Default.(func() time.Time)
	// ordersub.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	ordersub.UpdateDefaultUpdateTime = ordersubDescUpdateTime.UpdateDefault.(func() time.Time)
	refundMixin := schema.Refund{}.Mixin()
	refundMixinFields0 := refundMixin[0].Fields()
	_ = refundMixinFields0
	refundFields := schema.Refund{}.Fields()
	_ = refundFields
	// refundDescCreateTime is the schema descriptor for create_time field.
	refundDescCreateTime := refundMixinFields0[0].Descriptor()
	// refund.DefaultCreateTime holds the default value on creation for the create_time field.
	refund.DefaultCreateTime = refundDescCreateTime.Default.(func() time.Time)
	// refundDescUpdateTime is the schema descriptor for update_time field.
	refundDescUpdateTime := refundMixinFields0[1].Descriptor()
	// refund.DefaultUpdateTime holds the default value on creation for the update_time field.
	refund.DefaultUpdateTime = refundDescUpdateTime.Default.(func() time.Time)
	// refund.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	refund.UpdateDefaultUpdateTime = refundDescUpdateTime.UpdateDefault.(func() time.Time)
	saleexplainMixin := schema.SaleExplain{}.Mixin()
	saleexplainMixinFields0 := saleexplainMixin[0].Fields()
	_ = saleexplainMixinFields0
	saleexplainFields := schema.SaleExplain{}.Fields()
	_ = saleexplainFields
	// saleexplainDescCreateTime is the schema descriptor for create_time field.
	saleexplainDescCreateTime := saleexplainMixinFields0[0].Descriptor()
	// saleexplain.DefaultCreateTime holds the default value on creation for the create_time field.
	saleexplain.DefaultCreateTime = saleexplainDescCreateTime.Default.(func() time.Time)
	// saleexplainDescUpdateTime is the schema descriptor for update_time field.
	saleexplainDescUpdateTime := saleexplainMixinFields0[1].Descriptor()
	// saleexplain.DefaultUpdateTime holds the default value on creation for the update_time field.
	saleexplain.DefaultUpdateTime = saleexplainDescUpdateTime.Default.(func() time.Time)
	// saleexplain.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	saleexplain.UpdateDefaultUpdateTime = saleexplainDescUpdateTime.UpdateDefault.(func() time.Time)
	skuMixin := schema.Sku{}.Mixin()
	skuMixinFields0 := skuMixin[0].Fields()
	_ = skuMixinFields0
	skuFields := schema.Sku{}.Fields()
	_ = skuFields
	// skuDescCreateTime is the schema descriptor for create_time field.
	skuDescCreateTime := skuMixinFields0[0].Descriptor()
	// sku.DefaultCreateTime holds the default value on creation for the create_time field.
	sku.DefaultCreateTime = skuDescCreateTime.Default.(func() time.Time)
	// skuDescUpdateTime is the schema descriptor for update_time field.
	skuDescUpdateTime := skuMixinFields0[1].Descriptor()
	// sku.DefaultUpdateTime holds the default value on creation for the update_time field.
	sku.DefaultUpdateTime = skuDescUpdateTime.Default.(func() time.Time)
	// sku.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	sku.UpdateDefaultUpdateTime = skuDescUpdateTime.UpdateDefault.(func() time.Time)
	speckeyMixin := schema.SpecKey{}.Mixin()
	speckeyMixinFields0 := speckeyMixin[0].Fields()
	_ = speckeyMixinFields0
	speckeyFields := schema.SpecKey{}.Fields()
	_ = speckeyFields
	// speckeyDescCreateTime is the schema descriptor for create_time field.
	speckeyDescCreateTime := speckeyMixinFields0[0].Descriptor()
	// speckey.DefaultCreateTime holds the default value on creation for the create_time field.
	speckey.DefaultCreateTime = speckeyDescCreateTime.Default.(func() time.Time)
	// speckeyDescUpdateTime is the schema descriptor for update_time field.
	speckeyDescUpdateTime := speckeyMixinFields0[1].Descriptor()
	// speckey.DefaultUpdateTime holds the default value on creation for the update_time field.
	speckey.DefaultUpdateTime = speckeyDescUpdateTime.Default.(func() time.Time)
	// speckey.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	speckey.UpdateDefaultUpdateTime = speckeyDescUpdateTime.UpdateDefault.(func() time.Time)
	specvalueMixin := schema.SpecValue{}.Mixin()
	specvalueMixinFields0 := specvalueMixin[0].Fields()
	_ = specvalueMixinFields0
	specvalueFields := schema.SpecValue{}.Fields()
	_ = specvalueFields
	// specvalueDescCreateTime is the schema descriptor for create_time field.
	specvalueDescCreateTime := specvalueMixinFields0[0].Descriptor()
	// specvalue.DefaultCreateTime holds the default value on creation for the create_time field.
	specvalue.DefaultCreateTime = specvalueDescCreateTime.Default.(func() time.Time)
	// specvalueDescUpdateTime is the schema descriptor for update_time field.
	specvalueDescUpdateTime := specvalueMixinFields0[1].Descriptor()
	// specvalue.DefaultUpdateTime holds the default value on creation for the update_time field.
	specvalue.DefaultUpdateTime = specvalueDescUpdateTime.Default.(func() time.Time)
	// specvalue.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	specvalue.UpdateDefaultUpdateTime = specvalueDescUpdateTime.UpdateDefault.(func() time.Time)
	spuMixin := schema.Spu{}.Mixin()
	spuMixinFields0 := spuMixin[0].Fields()
	_ = spuMixinFields0
	spuFields := schema.Spu{}.Fields()
	_ = spuFields
	// spuDescCreateTime is the schema descriptor for create_time field.
	spuDescCreateTime := spuMixinFields0[0].Descriptor()
	// spu.DefaultCreateTime holds the default value on creation for the create_time field.
	spu.DefaultCreateTime = spuDescCreateTime.Default.(func() time.Time)
	// spuDescUpdateTime is the schema descriptor for update_time field.
	spuDescUpdateTime := spuMixinFields0[1].Descriptor()
	// spu.DefaultUpdateTime holds the default value on creation for the update_time field.
	spu.DefaultUpdateTime = spuDescUpdateTime.Default.(func() time.Time)
	// spu.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	spu.UpdateDefaultUpdateTime = spuDescUpdateTime.UpdateDefault.(func() time.Time)
	spudetailimgMixin := schema.SpuDetailImg{}.Mixin()
	spudetailimgMixinFields0 := spudetailimgMixin[0].Fields()
	_ = spudetailimgMixinFields0
	spudetailimgFields := schema.SpuDetailImg{}.Fields()
	_ = spudetailimgFields
	// spudetailimgDescCreateTime is the schema descriptor for create_time field.
	spudetailimgDescCreateTime := spudetailimgMixinFields0[0].Descriptor()
	// spudetailimg.DefaultCreateTime holds the default value on creation for the create_time field.
	spudetailimg.DefaultCreateTime = spudetailimgDescCreateTime.Default.(func() time.Time)
	// spudetailimgDescUpdateTime is the schema descriptor for update_time field.
	spudetailimgDescUpdateTime := spudetailimgMixinFields0[1].Descriptor()
	// spudetailimg.DefaultUpdateTime holds the default value on creation for the update_time field.
	spudetailimg.DefaultUpdateTime = spudetailimgDescUpdateTime.Default.(func() time.Time)
	// spudetailimg.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	spudetailimg.UpdateDefaultUpdateTime = spudetailimgDescUpdateTime.UpdateDefault.(func() time.Time)
	spuimgMixin := schema.SpuImg{}.Mixin()
	spuimgMixinFields0 := spuimgMixin[0].Fields()
	_ = spuimgMixinFields0
	spuimgFields := schema.SpuImg{}.Fields()
	_ = spuimgFields
	// spuimgDescCreateTime is the schema descriptor for create_time field.
	spuimgDescCreateTime := spuimgMixinFields0[0].Descriptor()
	// spuimg.DefaultCreateTime holds the default value on creation for the create_time field.
	spuimg.DefaultCreateTime = spuimgDescCreateTime.Default.(func() time.Time)
	// spuimgDescUpdateTime is the schema descriptor for update_time field.
	spuimgDescUpdateTime := spuimgMixinFields0[1].Descriptor()
	// spuimg.DefaultUpdateTime holds the default value on creation for the update_time field.
	spuimg.DefaultUpdateTime = spuimgDescUpdateTime.Default.(func() time.Time)
	// spuimg.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	spuimg.UpdateDefaultUpdateTime = spuimgDescUpdateTime.UpdateDefault.(func() time.Time)
	tagMixin := schema.Tag{}.Mixin()
	tagMixinFields0 := tagMixin[0].Fields()
	_ = tagMixinFields0
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescCreateTime is the schema descriptor for create_time field.
	tagDescCreateTime := tagMixinFields0[0].Descriptor()
	// tag.DefaultCreateTime holds the default value on creation for the create_time field.
	tag.DefaultCreateTime = tagDescCreateTime.Default.(func() time.Time)
	// tagDescUpdateTime is the schema descriptor for update_time field.
	tagDescUpdateTime := tagMixinFields0[1].Descriptor()
	// tag.DefaultUpdateTime holds the default value on creation for the update_time field.
	tag.DefaultUpdateTime = tagDescUpdateTime.Default.(func() time.Time)
	// tag.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	tag.UpdateDefaultUpdateTime = tagDescUpdateTime.UpdateDefault.(func() time.Time)
	themeMixin := schema.Theme{}.Mixin()
	themeMixinFields0 := themeMixin[0].Fields()
	_ = themeMixinFields0
	themeFields := schema.Theme{}.Fields()
	_ = themeFields
	// themeDescCreateTime is the schema descriptor for create_time field.
	themeDescCreateTime := themeMixinFields0[0].Descriptor()
	// theme.DefaultCreateTime holds the default value on creation for the create_time field.
	theme.DefaultCreateTime = themeDescCreateTime.Default.(func() time.Time)
	// themeDescUpdateTime is the schema descriptor for update_time field.
	themeDescUpdateTime := themeMixinFields0[1].Descriptor()
	// theme.DefaultUpdateTime holds the default value on creation for the update_time field.
	theme.DefaultUpdateTime = themeDescUpdateTime.Default.(func() time.Time)
	// theme.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	theme.UpdateDefaultUpdateTime = themeDescUpdateTime.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[4].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(int)
	usercouponMixin := schema.UserCoupon{}.Mixin()
	usercouponMixinFields0 := usercouponMixin[0].Fields()
	_ = usercouponMixinFields0
	usercouponFields := schema.UserCoupon{}.Fields()
	_ = usercouponFields
	// usercouponDescCreateTime is the schema descriptor for create_time field.
	usercouponDescCreateTime := usercouponMixinFields0[0].Descriptor()
	// usercoupon.DefaultCreateTime holds the default value on creation for the create_time field.
	usercoupon.DefaultCreateTime = usercouponDescCreateTime.Default.(func() time.Time)
	// usercouponDescUpdateTime is the schema descriptor for update_time field.
	usercouponDescUpdateTime := usercouponMixinFields0[1].Descriptor()
	// usercoupon.DefaultUpdateTime holds the default value on creation for the update_time field.
	usercoupon.DefaultUpdateTime = usercouponDescUpdateTime.Default.(func() time.Time)
	// usercoupon.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	usercoupon.UpdateDefaultUpdateTime = usercouponDescUpdateTime.UpdateDefault.(func() time.Time)
	// usercouponDescStatus is the schema descriptor for status field.
	usercouponDescStatus := usercouponFields[2].Descriptor()
	// usercoupon.DefaultStatus holds the default value on creation for the status field.
	usercoupon.DefaultStatus = usercouponDescStatus.Default.(int)
	userfavorMixin := schema.UserFavor{}.Mixin()
	userfavorMixinFields0 := userfavorMixin[0].Fields()
	_ = userfavorMixinFields0
	userfavorFields := schema.UserFavor{}.Fields()
	_ = userfavorFields
	// userfavorDescCreateTime is the schema descriptor for create_time field.
	userfavorDescCreateTime := userfavorMixinFields0[0].Descriptor()
	// userfavor.DefaultCreateTime holds the default value on creation for the create_time field.
	userfavor.DefaultCreateTime = userfavorDescCreateTime.Default.(func() time.Time)
	// userfavorDescUpdateTime is the schema descriptor for update_time field.
	userfavorDescUpdateTime := userfavorMixinFields0[1].Descriptor()
	// userfavor.DefaultUpdateTime holds the default value on creation for the update_time field.
	userfavor.DefaultUpdateTime = userfavorDescUpdateTime.Default.(func() time.Time)
	// userfavor.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	userfavor.UpdateDefaultUpdateTime = userfavorDescUpdateTime.UpdateDefault.(func() time.Time)
	// userfavorDescStatus is the schema descriptor for status field.
	userfavorDescStatus := userfavorFields[2].Descriptor()
	// userfavor.DefaultStatus holds the default value on creation for the status field.
	userfavor.DefaultStatus = userfavorDescStatus.Default.(int)
	userinfoMixin := schema.UserInfo{}.Mixin()
	userinfoMixinFields0 := userinfoMixin[0].Fields()
	_ = userinfoMixinFields0
	userinfoFields := schema.UserInfo{}.Fields()
	_ = userinfoFields
	// userinfoDescCreateTime is the schema descriptor for create_time field.
	userinfoDescCreateTime := userinfoMixinFields0[0].Descriptor()
	// userinfo.DefaultCreateTime holds the default value on creation for the create_time field.
	userinfo.DefaultCreateTime = userinfoDescCreateTime.Default.(func() time.Time)
	// userinfoDescUpdateTime is the schema descriptor for update_time field.
	userinfoDescUpdateTime := userinfoMixinFields0[1].Descriptor()
	// userinfo.DefaultUpdateTime holds the default value on creation for the update_time field.
	userinfo.DefaultUpdateTime = userinfoDescUpdateTime.Default.(func() time.Time)
	// userinfo.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	userinfo.UpdateDefaultUpdateTime = userinfoDescUpdateTime.UpdateDefault.(func() time.Time)
	userpointMixin := schema.UserPoint{}.Mixin()
	userpointMixinFields0 := userpointMixin[0].Fields()
	_ = userpointMixinFields0
	userpointFields := schema.UserPoint{}.Fields()
	_ = userpointFields
	// userpointDescCreateTime is the schema descriptor for create_time field.
	userpointDescCreateTime := userpointMixinFields0[0].Descriptor()
	// userpoint.DefaultCreateTime holds the default value on creation for the create_time field.
	userpoint.DefaultCreateTime = userpointDescCreateTime.Default.(func() time.Time)
	// userpointDescUpdateTime is the schema descriptor for update_time field.
	userpointDescUpdateTime := userpointMixinFields0[1].Descriptor()
	// userpoint.DefaultUpdateTime holds the default value on creation for the update_time field.
	userpoint.DefaultUpdateTime = userpointDescUpdateTime.Default.(func() time.Time)
	// userpoint.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	userpoint.UpdateDefaultUpdateTime = userpointDescUpdateTime.UpdateDefault.(func() time.Time)
	userpointdetailMixin := schema.UserPointDetail{}.Mixin()
	userpointdetailMixinFields0 := userpointdetailMixin[0].Fields()
	_ = userpointdetailMixinFields0
	userpointdetailFields := schema.UserPointDetail{}.Fields()
	_ = userpointdetailFields
	// userpointdetailDescCreateTime is the schema descriptor for create_time field.
	userpointdetailDescCreateTime := userpointdetailMixinFields0[0].Descriptor()
	// userpointdetail.DefaultCreateTime holds the default value on creation for the create_time field.
	userpointdetail.DefaultCreateTime = userpointdetailDescCreateTime.Default.(func() time.Time)
	// userpointdetailDescUpdateTime is the schema descriptor for update_time field.
	userpointdetailDescUpdateTime := userpointdetailMixinFields0[1].Descriptor()
	// userpointdetail.DefaultUpdateTime holds the default value on creation for the update_time field.
	userpointdetail.DefaultUpdateTime = userpointdetailDescUpdateTime.Default.(func() time.Time)
	// userpointdetail.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	userpointdetail.UpdateDefaultUpdateTime = userpointdetailDescUpdateTime.UpdateDefault.(func() time.Time)
	userwalletMixin := schema.UserWallet{}.Mixin()
	userwalletMixinFields0 := userwalletMixin[0].Fields()
	_ = userwalletMixinFields0
	userwalletFields := schema.UserWallet{}.Fields()
	_ = userwalletFields
	// userwalletDescCreateTime is the schema descriptor for create_time field.
	userwalletDescCreateTime := userwalletMixinFields0[0].Descriptor()
	// userwallet.DefaultCreateTime holds the default value on creation for the create_time field.
	userwallet.DefaultCreateTime = userwalletDescCreateTime.Default.(func() time.Time)
	// userwalletDescUpdateTime is the schema descriptor for update_time field.
	userwalletDescUpdateTime := userwalletMixinFields0[1].Descriptor()
	// userwallet.DefaultUpdateTime holds the default value on creation for the update_time field.
	userwallet.DefaultUpdateTime = userwalletDescUpdateTime.Default.(func() time.Time)
	// userwallet.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	userwallet.UpdateDefaultUpdateTime = userwalletDescUpdateTime.UpdateDefault.(func() time.Time)
	userwalletdetailMixin := schema.UserWalletDetail{}.Mixin()
	userwalletdetailMixinFields0 := userwalletdetailMixin[0].Fields()
	_ = userwalletdetailMixinFields0
	userwalletdetailFields := schema.UserWalletDetail{}.Fields()
	_ = userwalletdetailFields
	// userwalletdetailDescCreateTime is the schema descriptor for create_time field.
	userwalletdetailDescCreateTime := userwalletdetailMixinFields0[0].Descriptor()
	// userwalletdetail.DefaultCreateTime holds the default value on creation for the create_time field.
	userwalletdetail.DefaultCreateTime = userwalletdetailDescCreateTime.Default.(func() time.Time)
	// userwalletdetailDescUpdateTime is the schema descriptor for update_time field.
	userwalletdetailDescUpdateTime := userwalletdetailMixinFields0[1].Descriptor()
	// userwalletdetail.DefaultUpdateTime holds the default value on creation for the update_time field.
	userwalletdetail.DefaultUpdateTime = userwalletdetailDescUpdateTime.Default.(func() time.Time)
	// userwalletdetail.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	userwalletdetail.UpdateDefaultUpdateTime = userwalletdetailDescUpdateTime.UpdateDefault.(func() time.Time)
	// userwalletdetailDescOp is the schema descriptor for op field.
	userwalletdetailDescOp := userwalletdetailFields[1].Descriptor()
	// userwalletdetail.DefaultOp holds the default value on creation for the op field.
	userwalletdetail.DefaultOp = userwalletdetailDescOp.Default.(int)
	// userwalletdetailDescType is the schema descriptor for type field.
	userwalletdetailDescType := userwalletdetailFields[4].Descriptor()
	// userwalletdetail.DefaultType holds the default value on creation for the type field.
	userwalletdetail.DefaultType = userwalletdetailDescType.Default.(int)
}
