// Code generated by entc, DO NOT EDIT.

package model

import (
	"context"
	"errors"
	"fmt"
	"mall-go/app/app/service/internal/data/model/saleexplain"
	"mall-go/app/app/service/internal/data/model/spu"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SaleExplainCreate is the builder for creating a SaleExplain entity.
type SaleExplainCreate struct {
	config
	mutation *SaleExplainMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (sec *SaleExplainCreate) SetCreateTime(t time.Time) *SaleExplainCreate {
	sec.mutation.SetCreateTime(t)
	return sec
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (sec *SaleExplainCreate) SetNillableCreateTime(t *time.Time) *SaleExplainCreate {
	if t != nil {
		sec.SetCreateTime(*t)
	}
	return sec
}

// SetUpdateTime sets the "update_time" field.
func (sec *SaleExplainCreate) SetUpdateTime(t time.Time) *SaleExplainCreate {
	sec.mutation.SetUpdateTime(t)
	return sec
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (sec *SaleExplainCreate) SetNillableUpdateTime(t *time.Time) *SaleExplainCreate {
	if t != nil {
		sec.SetUpdateTime(*t)
	}
	return sec
}

// SetDeleteTime sets the "delete_time" field.
func (sec *SaleExplainCreate) SetDeleteTime(t time.Time) *SaleExplainCreate {
	sec.mutation.SetDeleteTime(t)
	return sec
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (sec *SaleExplainCreate) SetNillableDeleteTime(t *time.Time) *SaleExplainCreate {
	if t != nil {
		sec.SetDeleteTime(*t)
	}
	return sec
}

// SetFixed sets the "fixed" field.
func (sec *SaleExplainCreate) SetFixed(i int) *SaleExplainCreate {
	sec.mutation.SetFixed(i)
	return sec
}

// SetText sets the "text" field.
func (sec *SaleExplainCreate) SetText(s string) *SaleExplainCreate {
	sec.mutation.SetText(s)
	return sec
}

// SetSpuID sets the "spu_id" field.
func (sec *SaleExplainCreate) SetSpuID(i int64) *SaleExplainCreate {
	sec.mutation.SetSpuID(i)
	return sec
}

// SetNillableSpuID sets the "spu_id" field if the given value is not nil.
func (sec *SaleExplainCreate) SetNillableSpuID(i *int64) *SaleExplainCreate {
	if i != nil {
		sec.SetSpuID(*i)
	}
	return sec
}

// SetIndex sets the "index" field.
func (sec *SaleExplainCreate) SetIndex(i int) *SaleExplainCreate {
	sec.mutation.SetIndex(i)
	return sec
}

// SetReplaceID sets the "replace_id" field.
func (sec *SaleExplainCreate) SetReplaceID(i int64) *SaleExplainCreate {
	sec.mutation.SetReplaceID(i)
	return sec
}

// SetSpu sets the "spu" edge to the Spu entity.
func (sec *SaleExplainCreate) SetSpu(s *Spu) *SaleExplainCreate {
	return sec.SetSpuID(s.ID)
}

// Mutation returns the SaleExplainMutation object of the builder.
func (sec *SaleExplainCreate) Mutation() *SaleExplainMutation {
	return sec.mutation
}

// Save creates the SaleExplain in the database.
func (sec *SaleExplainCreate) Save(ctx context.Context) (*SaleExplain, error) {
	var (
		err  error
		node *SaleExplain
	)
	sec.defaults()
	if len(sec.hooks) == 0 {
		if err = sec.check(); err != nil {
			return nil, err
		}
		node, err = sec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SaleExplainMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sec.check(); err != nil {
				return nil, err
			}
			sec.mutation = mutation
			if node, err = sec.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(sec.hooks) - 1; i >= 0; i-- {
			if sec.hooks[i] == nil {
				return nil, fmt.Errorf("model: uninitialized hook (forgotten import model/runtime?)")
			}
			mut = sec.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sec.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sec *SaleExplainCreate) SaveX(ctx context.Context) *SaleExplain {
	v, err := sec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sec *SaleExplainCreate) Exec(ctx context.Context) error {
	_, err := sec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sec *SaleExplainCreate) ExecX(ctx context.Context) {
	if err := sec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sec *SaleExplainCreate) defaults() {
	if _, ok := sec.mutation.CreateTime(); !ok {
		v := saleexplain.DefaultCreateTime()
		sec.mutation.SetCreateTime(v)
	}
	if _, ok := sec.mutation.UpdateTime(); !ok {
		v := saleexplain.DefaultUpdateTime()
		sec.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sec *SaleExplainCreate) check() error {
	if _, ok := sec.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`model: missing required field "create_time"`)}
	}
	if _, ok := sec.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`model: missing required field "update_time"`)}
	}
	if _, ok := sec.mutation.Fixed(); !ok {
		return &ValidationError{Name: "fixed", err: errors.New(`model: missing required field "fixed"`)}
	}
	if _, ok := sec.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`model: missing required field "text"`)}
	}
	if _, ok := sec.mutation.Index(); !ok {
		return &ValidationError{Name: "index", err: errors.New(`model: missing required field "index"`)}
	}
	if _, ok := sec.mutation.ReplaceID(); !ok {
		return &ValidationError{Name: "replace_id", err: errors.New(`model: missing required field "replace_id"`)}
	}
	return nil
}

func (sec *SaleExplainCreate) sqlSave(ctx context.Context) (*SaleExplain, error) {
	_node, _spec := sec.createSpec()
	if err := sqlgraph.CreateNode(ctx, sec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	return _node, nil
}

func (sec *SaleExplainCreate) createSpec() (*SaleExplain, *sqlgraph.CreateSpec) {
	var (
		_node = &SaleExplain{config: sec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: saleexplain.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: saleexplain.FieldID,
			},
		}
	)
	if value, ok := sec.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: saleexplain.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := sec.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: saleexplain.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := sec.mutation.DeleteTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: saleexplain.FieldDeleteTime,
		})
		_node.DeleteTime = value
	}
	if value, ok := sec.mutation.Fixed(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: saleexplain.FieldFixed,
		})
		_node.Fixed = value
	}
	if value, ok := sec.mutation.Text(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: saleexplain.FieldText,
		})
		_node.Text = value
	}
	if value, ok := sec.mutation.Index(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: saleexplain.FieldIndex,
		})
		_node.Index = value
	}
	if value, ok := sec.mutation.ReplaceID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: saleexplain.FieldReplaceID,
		})
		_node.ReplaceID = value
	}
	if nodes := sec.mutation.SpuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   saleexplain.SpuTable,
			Columns: []string{saleexplain.SpuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: spu.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SpuID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SaleExplainCreateBulk is the builder for creating many SaleExplain entities in bulk.
type SaleExplainCreateBulk struct {
	config
	builders []*SaleExplainCreate
}

// Save creates the SaleExplain entities in the database.
func (secb *SaleExplainCreateBulk) Save(ctx context.Context) ([]*SaleExplain, error) {
	specs := make([]*sqlgraph.CreateSpec, len(secb.builders))
	nodes := make([]*SaleExplain, len(secb.builders))
	mutators := make([]Mutator, len(secb.builders))
	for i := range secb.builders {
		func(i int, root context.Context) {
			builder := secb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SaleExplainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, secb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, secb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, secb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (secb *SaleExplainCreateBulk) SaveX(ctx context.Context) []*SaleExplain {
	v, err := secb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (secb *SaleExplainCreateBulk) Exec(ctx context.Context) error {
	_, err := secb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (secb *SaleExplainCreateBulk) ExecX(ctx context.Context) {
	if err := secb.Exec(ctx); err != nil {
		panic(err)
	}
}
