// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Coupon is the predicate function for coupon builders.
type Coupon func(*sql.Selector)

// CouponTemplate is the predicate function for coupontemplate builders.
type CouponTemplate func(*sql.Selector)

// CouponType is the predicate function for coupontype builders.
type CouponType func(*sql.Selector)

// UserCoupon is the predicate function for usercoupon builders.
type UserCoupon func(*sql.Selector)
