// Code generated by entc, DO NOT EDIT.

package theme

import (
	"time"
)

const (
	// Label holds the string label denoting the theme type in the database.
	Label = "theme"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTplName holds the string denoting the tpl_name field in the database.
	FieldTplName = "tpl_name"
	// FieldEntranceImg holds the string denoting the entrance_img field in the database.
	FieldEntranceImg = "entrance_img"
	// FieldExtend holds the string denoting the extend field in the database.
	FieldExtend = "extend"
	// FieldInternalTopImg holds the string denoting the internal_top_img field in the database.
	FieldInternalTopImg = "internal_top_img"
	// FieldTitleImg holds the string denoting the title_img field in the database.
	FieldTitleImg = "title_img"
	// FieldOnline holds the string denoting the online field in the database.
	FieldOnline = "online"
	// EdgeSpu holds the string denoting the spu edge name in mutations.
	EdgeSpu = "spu"
	// Table holds the table name of the theme in the database.
	Table = "theme"
	// SpuTable is the table that holds the spu relation/edge. The primary key declared below.
	SpuTable = "theme_spu"
	// SpuInverseTable is the table name for the Spu entity.
	// It exists in this package in order to avoid circular dependency with the "spu" package.
	SpuInverseTable = "spu"
)

// Columns holds all SQL columns for theme fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldTitle,
	FieldDescription,
	FieldName,
	FieldTplName,
	FieldEntranceImg,
	FieldExtend,
	FieldInternalTopImg,
	FieldTitleImg,
	FieldOnline,
}

var (
	// SpuPrimaryKey and SpuColumn2 are the table columns denoting the
	// primary key for the spu relation (M2M).
	SpuPrimaryKey = []string{"theme_id", "spu_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)
