// Code generated by entc, DO NOT EDIT.

package model

import (
	"context"
	"errors"
	"fmt"
	"mall-go/internal/data/model/userpoint"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserPointCreate is the builder for creating a UserPoint entity.
type UserPointCreate struct {
	config
	mutation *UserPointMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (upc *UserPointCreate) SetCreateTime(t time.Time) *UserPointCreate {
	upc.mutation.SetCreateTime(t)
	return upc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (upc *UserPointCreate) SetNillableCreateTime(t *time.Time) *UserPointCreate {
	if t != nil {
		upc.SetCreateTime(*t)
	}
	return upc
}

// SetUpdateTime sets the "update_time" field.
func (upc *UserPointCreate) SetUpdateTime(t time.Time) *UserPointCreate {
	upc.mutation.SetUpdateTime(t)
	return upc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (upc *UserPointCreate) SetNillableUpdateTime(t *time.Time) *UserPointCreate {
	if t != nil {
		upc.SetUpdateTime(*t)
	}
	return upc
}

// SetDeleteTime sets the "delete_time" field.
func (upc *UserPointCreate) SetDeleteTime(t time.Time) *UserPointCreate {
	upc.mutation.SetDeleteTime(t)
	return upc
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (upc *UserPointCreate) SetNillableDeleteTime(t *time.Time) *UserPointCreate {
	if t != nil {
		upc.SetDeleteTime(*t)
	}
	return upc
}

// SetValue sets the "value" field.
func (upc *UserPointCreate) SetValue(i int) *UserPointCreate {
	upc.mutation.SetValue(i)
	return upc
}

// SetStatus sets the "status" field.
func (upc *UserPointCreate) SetStatus(i int8) *UserPointCreate {
	upc.mutation.SetStatus(i)
	return upc
}

// SetID sets the "id" field.
func (upc *UserPointCreate) SetID(i int64) *UserPointCreate {
	upc.mutation.SetID(i)
	return upc
}

// Mutation returns the UserPointMutation object of the builder.
func (upc *UserPointCreate) Mutation() *UserPointMutation {
	return upc.mutation
}

// Save creates the UserPoint in the database.
func (upc *UserPointCreate) Save(ctx context.Context) (*UserPoint, error) {
	var (
		err  error
		node *UserPoint
	)
	upc.defaults()
	if len(upc.hooks) == 0 {
		if err = upc.check(); err != nil {
			return nil, err
		}
		node, err = upc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserPointMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = upc.check(); err != nil {
				return nil, err
			}
			upc.mutation = mutation
			if node, err = upc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(upc.hooks) - 1; i >= 0; i-- {
			if upc.hooks[i] == nil {
				return nil, fmt.Errorf("model: uninitialized hook (forgotten import model/runtime?)")
			}
			mut = upc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, upc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (upc *UserPointCreate) SaveX(ctx context.Context) *UserPoint {
	v, err := upc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (upc *UserPointCreate) Exec(ctx context.Context) error {
	_, err := upc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upc *UserPointCreate) ExecX(ctx context.Context) {
	if err := upc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (upc *UserPointCreate) defaults() {
	if _, ok := upc.mutation.CreateTime(); !ok {
		v := userpoint.DefaultCreateTime()
		upc.mutation.SetCreateTime(v)
	}
	if _, ok := upc.mutation.UpdateTime(); !ok {
		v := userpoint.DefaultUpdateTime()
		upc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upc *UserPointCreate) check() error {
	if _, ok := upc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`model: missing required field "create_time"`)}
	}
	if _, ok := upc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`model: missing required field "update_time"`)}
	}
	if _, ok := upc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`model: missing required field "value"`)}
	}
	if _, ok := upc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`model: missing required field "status"`)}
	}
	return nil
}

func (upc *UserPointCreate) sqlSave(ctx context.Context) (*UserPoint, error) {
	_node, _spec := upc.createSpec()
	if err := sqlgraph.CreateNode(ctx, upc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	return _node, nil
}

func (upc *UserPointCreate) createSpec() (*UserPoint, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPoint{config: upc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: userpoint.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: userpoint.FieldID,
			},
		}
	)
	if id, ok := upc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := upc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userpoint.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := upc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userpoint.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := upc.mutation.DeleteTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userpoint.FieldDeleteTime,
		})
		_node.DeleteTime = value
	}
	if value, ok := upc.mutation.Value(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userpoint.FieldValue,
		})
		_node.Value = value
	}
	if value, ok := upc.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: userpoint.FieldStatus,
		})
		_node.Status = value
	}
	return _node, _spec
}

// UserPointCreateBulk is the builder for creating many UserPoint entities in bulk.
type UserPointCreateBulk struct {
	config
	builders []*UserPointCreate
}

// Save creates the UserPoint entities in the database.
func (upcb *UserPointCreateBulk) Save(ctx context.Context) ([]*UserPoint, error) {
	specs := make([]*sqlgraph.CreateSpec, len(upcb.builders))
	nodes := make([]*UserPoint, len(upcb.builders))
	mutators := make([]Mutator, len(upcb.builders))
	for i := range upcb.builders {
		func(i int, root context.Context) {
			builder := upcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPointMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, upcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, upcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, upcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (upcb *UserPointCreateBulk) SaveX(ctx context.Context) []*UserPoint {
	v, err := upcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (upcb *UserPointCreateBulk) Exec(ctx context.Context) error {
	_, err := upcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upcb *UserPointCreateBulk) ExecX(ctx context.Context) {
	if err := upcb.Exec(ctx); err != nil {
		panic(err)
	}
}
