version: '3'
services:
  mall-go:
    image: mall-go:0.1.0
    ports:
      - 80:80
    depends_on:
      - user-db

  user-db:
    image: mysql:8
    hostname: user-db
    environment:
      MYSQL_ROOT_PASSWORD: dangerous

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper