// Code generated by ent, DO NOT EDIT.

package theme

import (
	"mall-go/app/app/service/internal/data/model/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreateTime), v))
	})
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdateTime), v))
	})
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeleteTime), v))
	})
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTitle), v))
	})
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDescription), v))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// TplName applies equality check predicate on the "tpl_name" field. It's identical to TplNameEQ.
func TplName(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTplName), v))
	})
}

// EntranceImg applies equality check predicate on the "entrance_img" field. It's identical to EntranceImgEQ.
func EntranceImg(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEntranceImg), v))
	})
}

// Extend applies equality check predicate on the "extend" field. It's identical to ExtendEQ.
func Extend(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExtend), v))
	})
}

// InternalTopImg applies equality check predicate on the "internal_top_img" field. It's identical to InternalTopImgEQ.
func InternalTopImg(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInternalTopImg), v))
	})
}

// TitleImg applies equality check predicate on the "title_img" field. It's identical to TitleImgEQ.
func TitleImg(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTitleImg), v))
	})
}

// Online applies equality check predicate on the "online" field. It's identical to OnlineEQ.
func Online(v int) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOnline), v))
	})
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreateTime), v))
	})
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreateTime), v))
	})
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreateTime), v...))
	})
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreateTime), v...))
	})
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreateTime), v))
	})
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreateTime), v))
	})
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreateTime), v))
	})
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreateTime), v))
	})
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdateTime), v...))
	})
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdateTime), v...))
	})
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdateTime), v))
	})
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeleteTime), v))
	})
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDeleteTime), v))
	})
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDeleteTime), v...))
	})
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDeleteTime), v...))
	})
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDeleteTime), v))
	})
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDeleteTime), v))
	})
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDeleteTime), v))
	})
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDeleteTime), v))
	})
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldDeleteTime)))
	})
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldDeleteTime)))
	})
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTitle), v))
	})
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTitle), v))
	})
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTitle), v...))
	})
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTitle), v...))
	})
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTitle), v))
	})
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTitle), v))
	})
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTitle), v))
	})
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTitle), v))
	})
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTitle), v))
	})
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTitle), v))
	})
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTitle), v))
	})
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTitle), v))
	})
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTitle), v))
	})
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDescription), v))
	})
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDescription), v))
	})
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDescription), v...))
	})
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDescription), v...))
	})
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDescription), v))
	})
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDescription), v))
	})
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDescription), v))
	})
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDescription), v))
	})
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDescription), v))
	})
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDescription), v))
	})
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDescription), v))
	})
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDescription), v))
	})
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDescription), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// TplNameEQ applies the EQ predicate on the "tpl_name" field.
func TplNameEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTplName), v))
	})
}

// TplNameNEQ applies the NEQ predicate on the "tpl_name" field.
func TplNameNEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTplName), v))
	})
}

// TplNameIn applies the In predicate on the "tpl_name" field.
func TplNameIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTplName), v...))
	})
}

// TplNameNotIn applies the NotIn predicate on the "tpl_name" field.
func TplNameNotIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTplName), v...))
	})
}

// TplNameGT applies the GT predicate on the "tpl_name" field.
func TplNameGT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTplName), v))
	})
}

// TplNameGTE applies the GTE predicate on the "tpl_name" field.
func TplNameGTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTplName), v))
	})
}

// TplNameLT applies the LT predicate on the "tpl_name" field.
func TplNameLT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTplName), v))
	})
}

// TplNameLTE applies the LTE predicate on the "tpl_name" field.
func TplNameLTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTplName), v))
	})
}

// TplNameContains applies the Contains predicate on the "tpl_name" field.
func TplNameContains(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTplName), v))
	})
}

// TplNameHasPrefix applies the HasPrefix predicate on the "tpl_name" field.
func TplNameHasPrefix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTplName), v))
	})
}

// TplNameHasSuffix applies the HasSuffix predicate on the "tpl_name" field.
func TplNameHasSuffix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTplName), v))
	})
}

// TplNameEqualFold applies the EqualFold predicate on the "tpl_name" field.
func TplNameEqualFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTplName), v))
	})
}

// TplNameContainsFold applies the ContainsFold predicate on the "tpl_name" field.
func TplNameContainsFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTplName), v))
	})
}

// EntranceImgEQ applies the EQ predicate on the "entrance_img" field.
func EntranceImgEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEntranceImg), v))
	})
}

// EntranceImgNEQ applies the NEQ predicate on the "entrance_img" field.
func EntranceImgNEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldEntranceImg), v))
	})
}

// EntranceImgIn applies the In predicate on the "entrance_img" field.
func EntranceImgIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldEntranceImg), v...))
	})
}

// EntranceImgNotIn applies the NotIn predicate on the "entrance_img" field.
func EntranceImgNotIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldEntranceImg), v...))
	})
}

// EntranceImgGT applies the GT predicate on the "entrance_img" field.
func EntranceImgGT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldEntranceImg), v))
	})
}

// EntranceImgGTE applies the GTE predicate on the "entrance_img" field.
func EntranceImgGTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldEntranceImg), v))
	})
}

// EntranceImgLT applies the LT predicate on the "entrance_img" field.
func EntranceImgLT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldEntranceImg), v))
	})
}

// EntranceImgLTE applies the LTE predicate on the "entrance_img" field.
func EntranceImgLTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldEntranceImg), v))
	})
}

// EntranceImgContains applies the Contains predicate on the "entrance_img" field.
func EntranceImgContains(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldEntranceImg), v))
	})
}

// EntranceImgHasPrefix applies the HasPrefix predicate on the "entrance_img" field.
func EntranceImgHasPrefix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldEntranceImg), v))
	})
}

// EntranceImgHasSuffix applies the HasSuffix predicate on the "entrance_img" field.
func EntranceImgHasSuffix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldEntranceImg), v))
	})
}

// EntranceImgEqualFold applies the EqualFold predicate on the "entrance_img" field.
func EntranceImgEqualFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldEntranceImg), v))
	})
}

// EntranceImgContainsFold applies the ContainsFold predicate on the "entrance_img" field.
func EntranceImgContainsFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldEntranceImg), v))
	})
}

// ExtendEQ applies the EQ predicate on the "extend" field.
func ExtendEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExtend), v))
	})
}

// ExtendNEQ applies the NEQ predicate on the "extend" field.
func ExtendNEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldExtend), v))
	})
}

// ExtendIn applies the In predicate on the "extend" field.
func ExtendIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldExtend), v...))
	})
}

// ExtendNotIn applies the NotIn predicate on the "extend" field.
func ExtendNotIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldExtend), v...))
	})
}

// ExtendGT applies the GT predicate on the "extend" field.
func ExtendGT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldExtend), v))
	})
}

// ExtendGTE applies the GTE predicate on the "extend" field.
func ExtendGTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldExtend), v))
	})
}

// ExtendLT applies the LT predicate on the "extend" field.
func ExtendLT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldExtend), v))
	})
}

// ExtendLTE applies the LTE predicate on the "extend" field.
func ExtendLTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldExtend), v))
	})
}

// ExtendContains applies the Contains predicate on the "extend" field.
func ExtendContains(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldExtend), v))
	})
}

// ExtendHasPrefix applies the HasPrefix predicate on the "extend" field.
func ExtendHasPrefix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldExtend), v))
	})
}

// ExtendHasSuffix applies the HasSuffix predicate on the "extend" field.
func ExtendHasSuffix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldExtend), v))
	})
}

// ExtendEqualFold applies the EqualFold predicate on the "extend" field.
func ExtendEqualFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldExtend), v))
	})
}

// ExtendContainsFold applies the ContainsFold predicate on the "extend" field.
func ExtendContainsFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldExtend), v))
	})
}

// InternalTopImgEQ applies the EQ predicate on the "internal_top_img" field.
func InternalTopImgEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInternalTopImg), v))
	})
}

// InternalTopImgNEQ applies the NEQ predicate on the "internal_top_img" field.
func InternalTopImgNEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldInternalTopImg), v))
	})
}

// InternalTopImgIn applies the In predicate on the "internal_top_img" field.
func InternalTopImgIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldInternalTopImg), v...))
	})
}

// InternalTopImgNotIn applies the NotIn predicate on the "internal_top_img" field.
func InternalTopImgNotIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldInternalTopImg), v...))
	})
}

// InternalTopImgGT applies the GT predicate on the "internal_top_img" field.
func InternalTopImgGT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldInternalTopImg), v))
	})
}

// InternalTopImgGTE applies the GTE predicate on the "internal_top_img" field.
func InternalTopImgGTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldInternalTopImg), v))
	})
}

// InternalTopImgLT applies the LT predicate on the "internal_top_img" field.
func InternalTopImgLT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldInternalTopImg), v))
	})
}

// InternalTopImgLTE applies the LTE predicate on the "internal_top_img" field.
func InternalTopImgLTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldInternalTopImg), v))
	})
}

// InternalTopImgContains applies the Contains predicate on the "internal_top_img" field.
func InternalTopImgContains(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldInternalTopImg), v))
	})
}

// InternalTopImgHasPrefix applies the HasPrefix predicate on the "internal_top_img" field.
func InternalTopImgHasPrefix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldInternalTopImg), v))
	})
}

// InternalTopImgHasSuffix applies the HasSuffix predicate on the "internal_top_img" field.
func InternalTopImgHasSuffix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldInternalTopImg), v))
	})
}

// InternalTopImgEqualFold applies the EqualFold predicate on the "internal_top_img" field.
func InternalTopImgEqualFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldInternalTopImg), v))
	})
}

// InternalTopImgContainsFold applies the ContainsFold predicate on the "internal_top_img" field.
func InternalTopImgContainsFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldInternalTopImg), v))
	})
}

// TitleImgEQ applies the EQ predicate on the "title_img" field.
func TitleImgEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTitleImg), v))
	})
}

// TitleImgNEQ applies the NEQ predicate on the "title_img" field.
func TitleImgNEQ(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTitleImg), v))
	})
}

// TitleImgIn applies the In predicate on the "title_img" field.
func TitleImgIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTitleImg), v...))
	})
}

// TitleImgNotIn applies the NotIn predicate on the "title_img" field.
func TitleImgNotIn(vs ...string) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTitleImg), v...))
	})
}

// TitleImgGT applies the GT predicate on the "title_img" field.
func TitleImgGT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTitleImg), v))
	})
}

// TitleImgGTE applies the GTE predicate on the "title_img" field.
func TitleImgGTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTitleImg), v))
	})
}

// TitleImgLT applies the LT predicate on the "title_img" field.
func TitleImgLT(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTitleImg), v))
	})
}

// TitleImgLTE applies the LTE predicate on the "title_img" field.
func TitleImgLTE(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTitleImg), v))
	})
}

// TitleImgContains applies the Contains predicate on the "title_img" field.
func TitleImgContains(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTitleImg), v))
	})
}

// TitleImgHasPrefix applies the HasPrefix predicate on the "title_img" field.
func TitleImgHasPrefix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTitleImg), v))
	})
}

// TitleImgHasSuffix applies the HasSuffix predicate on the "title_img" field.
func TitleImgHasSuffix(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTitleImg), v))
	})
}

// TitleImgEqualFold applies the EqualFold predicate on the "title_img" field.
func TitleImgEqualFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTitleImg), v))
	})
}

// TitleImgContainsFold applies the ContainsFold predicate on the "title_img" field.
func TitleImgContainsFold(v string) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTitleImg), v))
	})
}

// OnlineEQ applies the EQ predicate on the "online" field.
func OnlineEQ(v int) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOnline), v))
	})
}

// OnlineNEQ applies the NEQ predicate on the "online" field.
func OnlineNEQ(v int) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldOnline), v))
	})
}

// OnlineIn applies the In predicate on the "online" field.
func OnlineIn(vs ...int) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldOnline), v...))
	})
}

// OnlineNotIn applies the NotIn predicate on the "online" field.
func OnlineNotIn(vs ...int) predicate.Theme {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Theme(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldOnline), v...))
	})
}

// OnlineGT applies the GT predicate on the "online" field.
func OnlineGT(v int) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldOnline), v))
	})
}

// OnlineGTE applies the GTE predicate on the "online" field.
func OnlineGTE(v int) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldOnline), v))
	})
}

// OnlineLT applies the LT predicate on the "online" field.
func OnlineLT(v int) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldOnline), v))
	})
}

// OnlineLTE applies the LTE predicate on the "online" field.
func OnlineLTE(v int) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldOnline), v))
	})
}

// HasThemeSpu applies the HasEdge predicate on the "theme_spu" edge.
func HasThemeSpu() predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ThemeSpuTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ThemeSpuTable, ThemeSpuColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasThemeSpuWith applies the HasEdge predicate on the "theme_spu" edge with a given conditions (other predicates).
func HasThemeSpuWith(preds ...predicate.ThemeSpu) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ThemeSpuInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ThemeSpuTable, ThemeSpuColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Theme) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Theme) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Theme) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		p(s.Not())
	})
}
